//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Customer.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Login;


public class Customer extends User, User
{
    private Object orders;
    public void ViewQueue()
    {
    
    }
    
    public void ViewDishes()
    {
    
    }
    
    public void PlaceOrder()
    {
    
    }
    
    public void Evaluate()
    {
    
    }
}
