//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : DailyDish.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Dish;


public class DailyDish extends Dish
{
    private Object remain;
    public void GetWindow()
    {
    
    }
    
    public void GetRemain()
    {
    
    }
    
    public void SetRemain()
    {
    
    }
    
    public class SelectingDish extends Dish.Dish
    {
        private Object isSelected;
        private Object number;
        public void Select()
        {
        
        }
        
        public void Diselect()
        {
        
        }
        
        public void IncreaseNum()
        {
        
        }
        
        public void DecreaseNum()
        {
        
        }
    }
}
