//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : DishesManager.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Dish;


public class DishesManager
{
    public void GetStockDishesInf()
    {
    
    }
    
    public void GetDailyDishesInf()
    {
    
    }
    
    public void GetSelectingDishesInf()
    {
    
    }
}
