//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Dish.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Dish;


public abstract class Dish
{
    private Object name;
    private Object type;
    private Object price;
    public void GetName()
    {
    
    }
    
    public void GetType()
    {
    
    }
    
    public void GetPrice()
    {
    
    }
}
