//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : StockDish.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Dish;


public class StockDish extends Dish
{
    private Object cost;
    public void SetName()
    {
    
    }
    
    public void SetType()
    {
    
    }
    
    public void SetPrice()
    {
    
    }
    
    public void SetCost()
    {
    
    }
}
