//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Subject.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Interface;


public abstract class Subject
{
    public void RegisterObserver()
    {
    
    }
    
    public void DeleteObserver()
    {
    
    }
    
    public void NotifyObserver()
    {
    
    }
    
    public void GetDishesInf()
    {
    
    }
}
