//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Cateen Managing System
//  @ File Name : User
//  @ Date : 2017.10.23
//  @ Author : CMS development group
//
//



public class Customer extends User
{
    public void ViewQueue()
    {
    
    }
    
    public void ViewDishes()
    {
    
    }
    
    public void PlaceOrder()
    {
    
    }
    
    public void Evaluate()
    {
    
    }
}
