//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen Managing System
//  @ File Name : User
//  @ Date : 2017.10.23
//  @ Author : CMS development group
//
//



public class Employee extends User
{
    public void SetAccounts()
    {
    
    }
    
    public void ApplyAddition()
    {
    
    }
    
    public void SetQueue()
    {
    
    }
    
    public void SetDishes()
    {
    
    }
    
    public void DealOrder()
    {
    
    }
    
    public void SetSales()
    {
    
    }
    
    public void ViewRank()
    {
    
    }
    
    public void ViewEvaluation()
    {
    
    }
}
