//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen Managing System
//  @ File Name : User
//  @ Date : 2017.10.23
//  @ Author : CMS development group
//
//



public class Manager extends User
{
    public void EditDishes()
    {
    
    }
    
    public void SetBudget()
    {
    
    }
    
    public void LaunchDiscount()
    {
    
    }
    
    public void SetSalary()
    {
    
    }
    
    public void SeeAccounts()
    {
    
    }
    
    public void ViewSales()
    {
    
    }
    
    public void SetRank()
    {
    
    }
    
    public void AddEmployee()
    {
    
    }
    
    public void DelEmployee()
    {
    
    }
    
    public void ViewEvaluation()
    {
    
    }
}
