//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Cateen Managing System
//  @ File Name : User
//  @ Date : 2017.10.23
//  @ Author : CMS development group
//
//



public class User
{
    private Object name;
    private Object ID;
    private Object role;
    private Object sex;
    private Object headshot;
    private Object password;
    public void SetName()
    {
    
    }
    
    public void ViewName()
    {
    
    }
    
    public void ViewID()
    {
    
    }
    
    public void ViewRole()
    {
    
    }
    
    public void SetSex()
    {
    
    }
    
    public void ViewSex()
    {
    
    }
    
    public void SetHeadshot()
    {
    
    }
    
    public void ViewHeadshot()
    {
    
    }
    
    public void SetPassword()
    {
    
    }
}
