//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : DishesData.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//




public class DishesData implements Interface.Subject
{
    public void GetDishesInf()
    {
    
    }
    
    public void GetDailyDishesInf()
    {
    
    }
}
