//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Sensor.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//




public class Sensor
{
    private Object dishesRemain;
    private Object crowdedness;
    public Object ldf;
}
