//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Window.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//




public class Window
{
    private Object winId;
    private Object name;
    private Object employees;
    private Object dishes;
    private Object crowdedness;
    public void AddEmployee()
    {
    
    }
    
    public void GetName()
    {
    
    }
    
    public void GetDishes()
    {
    
    }
    
    public void GetCrowdedness()
    {
    
    }
}
