//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : DishesSelector.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


public class DishesSelector
{
    private Object SelectingDishes;
    private Object selectedDishes;
    public void GetDishesInf()
    {
    
    }
    
    public void SelectDishes()
    {
    
    }
    
    public void GetSelectedDishes()
    {
    
    }
}
