//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Order.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


private class Order
{
    private Object orderID;
    private Object customerID;
    private Object dishes;
    private Object price;
    private Object orderTime;
    private Object expectedTime;
}
