//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : OrderProducer.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


public class OrderProducer
{
    private Object selectedDishes;
    private Object expecteTime;
    private void GetSystemTime()
    {
    
    }
    
    public void GetTotalPrice()
    {
    
    }
    
    public void ProduceOrder()
    {
    
    }
}
