//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : SelectDishesUI.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


public class SelectDishesUI
{
    private Object dishesSelector;
    public void ShowDishes()
    {
    
    }
    
    public void SelectButtonClick()
    {
    
    }
    
    public void FinishButtonClick()
    {
    
    }
}
