//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : CustomerMainUI.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


public class CustomerMainUI
{
    public Object customerOrderUI;
    public Object selectDishesUI;
    public void ToCustomerMainUI()
    {
    
    }
    
    public void OrderButtonClick()
    {
    
    }
}
