//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : OrderHandler.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Customer;


public class OrderHandler
{
}
