//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Displayment.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Interface;


public abstract class Displayment
{
    public void Update()
    {
    
    }
}
