//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Employee.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Login;


public class Employee extends User
{
    private Object ordersInf;
    private Object sales;
    public void SetDishes()
    {
    
    }
    
    public void AddSales()
    {
    
    }
    
    public void DealOrder()
    {
    
    }
    
    public void ViewRank()
    {
    
    }
    
    public void ViewEvaluation()
    {
    
    }
    
    public void ApplyAddition()
    {
    
    }
}
