//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : Manager.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Login;


public class Manager extends User, User
{
    public void EditDishes()
    {
    
    }
    
    public void SetSalary()
    {
    
    }
    
    public void SeeAccounts()
    {
    
    }
    
    public void SetRank()
    {
    
    }
    
    public void AddEmployee()
    {
    
    }
    
    public void DelEmployee()
    {
    
    }
    
    public void ViewEvaluation()
    {
    
    }
    
    public void SetBudget()
    {
    
    }
    
    public void LaunchDiscount()
    {
    
    }
}
