//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Canteen_Managing_System
//  @ File Name : User.java
//  @ Date : 2017/11/5
//  @ Author : CMS  Group
//
//



package Login;


public class User
{
    private Object name;
    private Object iD;
    private Object role;
    private Object sex;
    private Object password;
    public void SetName()
    {
    
    }
    
    public void GetName()
    {
    
    }
    
    public void GetID()
    {
    
    }
    
    public void GetRole()
    {
    
    }
    
    public void SetSex()
    {
    
    }
    
    public void GetSex()
    {
    
    }
    
    public void SetPassword()
    {
    
    }
}
